[package]
name = "runkv-client"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
runkv-common = { path = "../common" }
runkv-proto = { path = "../proto" }
tonic = "0.6.2"
