# Ref: https://github.com/zeke/semantic-pull-requests#configuration .
titleAndCommits: true
anyCommit: true
types:
  - feat
  - fix
  - docs
  - style
  - refactor
  - perf
  - test
  - build
  - ci
  - chore
  - revert
allowMergeCommits: true
allowMergeCommits: true