[workspace]
members = [
    "bench",
    "client",
    "common",
    "exhauster",
    "proto",
    "rudder",
    "storage",
    "tests",
    "wheel",
]

[profile.bench]
# Uncomment this line if you are generating flame graph.
debug = true

[profile.release]
debug = true
