extend = [{ path = "make/common.toml" }, { path = "make/minio.toml" }, { path = "make/jaeger.toml" },{ path = "make/prometheus.toml"}]

[env]
RUST_BACKTRACE = 1
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[config]
skip_core_tasks = true

[tasks.clean-all]
category = "Misc"
description = "Clean all downloaded binaries by deleting .run folder."
script = '''
#!@duckscript
rm -rf "${PREFIX}"
'''

[tasks.clean-data]
category = "Misc"
description = "Clean data by deleting files in .run/data folder."
script = '''
#!@duckscript
rm -rf "${PREFIX_DATA}/*"
'''

[tasks.d]
alias = "dev"

[tasks.dev]
category = "Develop"
description = "Start development envirorment."
dependencies = ["pre-dev"]
script = '''
#!@duckscript
echo success
'''

[tasks.pre-dev]
category = "Develop"
description = "Downloads necessary tools and build required components."
dependencies = ["download-minio", "download-mcli","download-prometheus", "clean-data"]
script = '''
#!/bin/bash
# run minio
tmux new -d -s runkv-minio ${PREFIX_BIN}/minio server --address 127.0.0.1:9000 --console-address 127.0.0.1:9090 ${PREFIX_DATA}
# run jaeger
tmux new -d -s runkv-jaeger ${PREFIX_BIN}/jaeger
# create test bucket
tmux new -d -s runkv-mcli ' \
${PREFIX_BIN}/mcli alias set local http://127.0.0.1:9000 minioadmin minioadmin ; \
${PREFIX_BIN}/mcli mb local/test ; \
'
'''

[tasks.k]
alias = "kill"

[tasks.kill]
category = "Develop"
description = "Kill development environment."
script = '''
#!/bin/bash
tmux kill-session -t runkv-minio
tmux kill-session -t runkv-jaeger
'''
