#!/bin/bash

if [ -z "$(which tmux)" ]; then
    echo "`tmux` is required, please install manually."
    exit 0
fi

if [ -z "$(which cargo-make)" ]; then
    echo "Installing cargo-make..."
    cargo install cargo-make --version "^0.35"
fi

if [ $# -eq 0 ] || [ "$1" == "-h" ] || [ "$1" ==  "--help" ]; then
    makers --list-all-steps
    exit 0
fi

makers --no-workspace "$@"