id = 0
host = "127.0.0.1"
port = 0
data_path = "data"
meta_path = "meta"
health_timeout = "10 s"

# [minio]
# url = 'minio://minioadmin:minioadmin@127.0.0.1:9000/runkv'

# [s3]
# bucket = "runkv"

[cache]
block_cache_capacity = "0 B"
meta_cache_capacity = "64 kiB"
