id = 201
host = "127.0.0.1"
port = 12501
data_path = "data"
meta_path = "meta"
poll_interval = "100ms"
heartbeat_interval = "100ms"

[rudder]
host = "127.0.0.1"
port = 12300

[minio]
url = 'minio://minioadmin:minioadmin@127.0.0.1:9000/runkv'

[s3]
bucket = "runkv"

[buffer]
write_buffer_capacity = "64 MiB"

[cache]
block_cache_capacity = "512 MiB"
meta_cache_capacity = "256 MiB"
