id = 1
host = "127.0.0.1"
port = 12301
data_path = "data"
meta_path = "meta"
health_timeout = "10 s"

[minio]
url = 'minio://minioadmin:minioadmin@127.0.0.1:9000/runkv'

[s3]
bucket = "runkv"

[cache]
meta_cache_capacity = "256 MiB"

[lsm_tree]
trigger_l0_compaction_ssts = 4
trigger_l0_compaction_interval = "1 s"
trigger_compaction_interval = "5 s"

sstable_capacity = "64 KiB"
block_capacity = "4 KiB"
restart_interval = 2
bloom_false_positive = 0.1

compaction_pin_ttl = "15 s"

[[lsm_tree.levels_options]]
compaction_strategy = "Overlap"
compression_algorithm = "None"

[[lsm_tree.levels_options]]
compaction_strategy = "NonOverlap"
compression_algorithm = "None"

[[lsm_tree.levels_options]]
compaction_strategy = "NonOverlap"
compression_algorithm = "None"

[[lsm_tree.levels_options]]
compaction_strategy = "NonOverlap"
compression_algorithm = "None"

[[lsm_tree.levels_options]]
compaction_strategy = "NonOverlap"
compression_algorithm = "Lz4"

[[lsm_tree.levels_options]]
compaction_strategy = "NonOverlap"
compression_algorithm = "Lz4"

[[lsm_tree.levels_options]]
compaction_strategy = "NonOverlap"
compression_algorithm = "Lz4"
