id = 101
host = "127.0.0.1"
port = 12401
log = ".run/log/"
data_path = "data"
meta_path = "meta"
poll_interval = "100ms"
heartbeat_interval = "100ms"

[rudder]
id = 1
host = "127.0.0.1"
port = 12301

[minio]
url = 'minio://minioadmin:minioadmin@127.0.0.1:9000/runkv'

[s3]
bucket = "runkv"

[buffer]
write_buffer_capacity = "64 MiB"

[cache]
block_cache_capacity = "512 MiB"
meta_cache_capacity = "256 MiB"

[raft_log_store]
log_dir_path = "/path/to/log/dir"
log_file_capacity = "64 MiB"
block_cache_capacity = "256 MiB"
persist = "sync"

[lsm_tree]
l1_capacity = "1 MiB"
level_multiplier = 10

trigger_l0_compaction_ssts = 4
trigger_l0_compaction_interval = "1 s"
trigger_compaction_interval = "5 s"

sstable_capacity = "64 KiB"
block_capacity = "4 KiB"
restart_interval = 2
bloom_false_positive = 0.1

compaction_pin_ttl = "15 s"

[[lsm_tree.levels_options]]
compaction_strategy = "Overlap"
compression_algorithm = "None"

[[lsm_tree.levels_options]]
compaction_strategy = "NonOverlap"
compression_algorithm = "None"

[[lsm_tree.levels_options]]
compaction_strategy = "NonOverlap"
compression_algorithm = "None"

[[lsm_tree.levels_options]]
compaction_strategy = "NonOverlap"
compression_algorithm = "None"

[[lsm_tree.levels_options]]
compaction_strategy = "NonOverlap"
compression_algorithm = "Lz4"

[[lsm_tree.levels_options]]
compaction_strategy = "NonOverlap"
compression_algorithm = "Lz4"

[[lsm_tree.levels_options]]
compaction_strategy = "NonOverlap"
compression_algorithm = "Lz4"
