{
 "title": "RunKV Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "KV Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Get - Instance Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.5, rate(kv_service_get_histogram_vec_bucket[1m]))) by (instance)",
     "legendFormat": "p50-{{instance}}"
    },
    {
     "expr": "avg(histogram_quantile(0.9, rate(kv_service_get_histogram_vec_bucket[1m]))) by (instance)",
     "legendFormat": "p90-{{instance}}"
    },
    {
     "expr": "avg(histogram_quantile(0.99, rate(kv_service_get_histogram_vec_bucket[1m]))) by (instance)",
     "legendFormat": "p99-{{instance}}"
    }
   ]
  },
  {
   "title": "Put - Instance Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.5, rate(kv_service_put_histogram_vec_bucket[1m]))) by (instance)",
     "legendFormat": "p50-{{instance}}"
    },
    {
     "expr": "avg(histogram_quantile(0.9, rate(kv_service_put_histogram_vec_bucket[1m]))) by (instance)",
     "legendFormat": "p90-{{instance}}"
    },
    {
     "expr": "avg(histogram_quantile(0.99, rate(kv_service_put_histogram_vec_bucket[1m]))) by (instance)",
     "legendFormat": "p99-{{instance}}"
    }
   ]
  },
  {
   "title": "Delete - Instance Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.5, rate(kv_service_delete_histogram_vec_bucket[1m]))) by (instance)",
     "legendFormat": "p50-{{instance}}"
    },
    {
     "expr": "avg(histogram_quantile(0.9, rate(kv_service_delete_histogram_vec_bucket[1m]))) by (instance)",
     "legendFormat": "p90-{{instance}}"
    },
    {
     "expr": "avg(histogram_quantile(0.99, rate(kv_service_delete_histogram_vec_bucket[1m]))) by (instance)",
     "legendFormat": "p99-{{instance}}"
    }
   ]
  },
  {
   "title": "Snapshot - Instance Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.5, rate(kv_service_snapshot_histogram_vec_bucket[1m]))) by (instance)",
     "legendFormat": "p50-{{instance}}"
    },
    {
     "expr": "avg(histogram_quantile(0.9, rate(kv_service_snapshot_histogram_vec_bucket[1m]))) by (instance)",
     "legendFormat": "p90-{{instance}}"
    },
    {
     "expr": "avg(histogram_quantile(0.99, rate(kv_service_snapshot_histogram_vec_bucket[1m]))) by (instance)",
     "legendFormat": "p99-{{instance}}"
    }
   ]
  },
  {
   "title": "Txn - Instance Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.5, rate(kv_service_txn_histogram_vec_bucket[1m]))) by (instance)",
     "legendFormat": "p50-{{instance}}"
    },
    {
     "expr": "avg(histogram_quantile(0.9, rate(kv_service_txn_histogram_vec_bucket[1m]))) by (instance)",
     "legendFormat": "p90-{{instance}}"
    },
    {
     "expr": "avg(histogram_quantile(0.99, rate(kv_service_txn_histogram_vec_bucket[1m]))) by (instance)",
     "legendFormat": "p99-{{instance}}"
    }
   ]
  },
  { "title": "Raft", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Append Log Entries - Instance Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.5, rate(raft_append_log_entries_histogram_vec_bucket[1m]))) by (instance)",
     "legendFormat": "p50-{{instance}}"
    },
    {
     "expr": "avg(histogram_quantile(0.9, rate(raft_append_log_entries_histogram_vec_bucket[1m]))) by (instance)",
     "legendFormat": "p90-{{instance}}"
    },
    {
     "expr": "avg(histogram_quantile(0.99, rate(raft_append_log_entries_histogram_vec_bucket[1m]))) by (instance)",
     "legendFormat": "p99-{{instance}}"
    }
   ]
  },
  {
   "title": "Apply Log Entries - Instance Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.5, rate(raft_apply_log_entries_histogram_vec_bucket[1m]))) by (instance)",
     "legendFormat": "p50-{{instance}}"
    },
    {
     "expr": "avg(histogram_quantile(0.9, rate(raft_apply_log_entries_histogram_vec_bucket[1m]))) by (instance)",
     "legendFormat": "p90-{{instance}}"
    },
    {
     "expr": "avg(histogram_quantile(0.99, rate(raft_apply_log_entries_histogram_vec_bucket[1m]))) by (instance)",
     "legendFormat": "p99-{{instance}}"
    }
   ]
  }
 ]
}