[env]
OS = { source = "${CARGO_MAKE_RUST_TARGET_OS}", mapping = { linux = "linux", macos = "darwin" } }
ARCH = { source = "${CARGO_MAKE_RUST_TARGET_ARCH}", mapping = { x86_64 = "amd64", aarch64 = "arm64" } }
SYSTEM = "${OS}-${ARCH}"
SYSTEM_AMD64 = "${OS}-amd64"                                                                            # some components do not support darwin-arm64 for now, use amd64 for fallback
PREFIX = "${PWD}/.run"
PREFIX_USR_BIN = "${PWD}/.bin"
PREFIX_BIN = "${PREFIX}/bin"
PREFIX_CONFIG = "${PREFIX}/config"
PREFIX_DATA = "${PREFIX}/data"
PREFIX_LOG = "${PREFIX}/log"
PREFIX_TMP = "${PREFIX}/tmp"

[tasks.prepare]
private = true
category = "Misc"
description = "Create .run folder for temporyary files and data."
script = '''
#!@duckscript
echo "Using ${PREFIX} as base folder."
mkdir "${PREFIX}"
mkdir "${PREFIX_BIN}"
mkdir "${PREFIX_TMP}"
mkdir "${PREFIX_DATA}"
mkdir "${PREFIX_LOG}"
'''
