extend = "common.toml"

[env]
MINIO_SYSTEM = "${SYSTEM}"
MCLI_DOWNLOAD_BIN = "https://dl.min.io/client/mc/release/${MINIO_SYSTEM}/mc"
MINIO_DOWNLOAD_BIN = "https://dl.min.io/server/minio/release/${MINIO_SYSTEM}/minio"

[tasks.download-minio]
category = "MinIO"
dependencies = ["prepare"]
description = "Download and extract MinIO."
script = '''
#!/bin/bash
set -e
if [ -f "${PREFIX_BIN}/minio" ]; then
    exit 0
fi
echo "MinIO Server not found, downloading"
curl -fL -o "${PREFIX_TMP}/minio" "${MINIO_DOWNLOAD_BIN}"
chmod +x "${PREFIX_TMP}/minio"
mv "${PREFIX_TMP}/minio" "${PREFIX_BIN}/minio"

"${PREFIX_BIN}/minio" --version
'''

[tasks.download-mcli]
category = "MinIO"
dependencies = ["prepare"]
description = "Download and extract MinIO Client."
script = '''
#!/bin/bash
set -e
if [ -f "${PREFIX_BIN}/mcli" ]; then
    exit 0
fi
echo "MinIO Client not found, downloading"
curl -fL -o "${PREFIX_TMP}/mcli" "${MCLI_DOWNLOAD_BIN}"
chmod +x "${PREFIX_TMP}/mcli"
mv "${PREFIX_TMP}/mcli" "${PREFIX_BIN}/mcli"

"${PREFIX_BIN}/mcli" --version
'''
