extend = "common.toml"

[env]
PROMETHEUS_SYSTEM = "${SYSTEM}" 
PROMETHEUS_DOWNLOAD_PATH = "${PREFIX_TMP}/prometheus.tar.gz"
PROMETHEUS_VERSION = "2.32.1"
PROMETHEUS_RELEASE = "prometheus-${PROMETHEUS_VERSION}.${PROMETHEUS_SYSTEM}"
PROMETHEUS_DOWNLOAD_TAR_GZ = "https://github.com/prometheus/prometheus/releases/download/v${PROMETHEUS_VERSION}/${PROMETHEUS_RELEASE}.tar.gz"

[tasks.download-prometheus]
category = "Metrics"
dependencies = ["prepare"]
description = "Download and extract Prometheus"
script = '''
#!/bin/bash
set -e
if [ -d "${PREFIX_BIN}/prometheus" ]; then
    exit 0
fi
if [ -e "${PREFIX_TMP}/prometheus.tar.gz" ]; then
else 
    curl -fL -o "${PROMETHEUS_DOWNLOAD_PATH}" "${PROMETHEUS_DOWNLOAD_TAR_GZ}"
fi
tar -xf "${PROMETHEUS_DOWNLOAD_PATH}" -C "${PREFIX_TMP}"
mv "${PREFIX_TMP}/${PROMETHEUS_RELEASE}" "${PREFIX_BIN}/prometheus"
'''