extend = "common.toml"

[env]
PROMETHEUS_SYSTEM = "${SYSTEM}" 
PROMETHEUS_DOWNLOAD_PATH = "${PREFIX_TMP}/prometheus.tar.gz"
PROMETHEUS_VERSION = "2.32.1"
PROMETHEUS_RELEASE = "prometheus-${PROMETHEUS_VERSION}.${PROMETHEUS_SYSTEM}"
PROMETHEUS_DOWNLOAD_TAR_GZ = "https://github.com/prometheus/prometheus/releases/download/v${PROMETHEUS_VERSION}/${PROMETHEUS_RELEASE}.tar.gz"

[tasks.download-prometheus]
category = "Metrics"
dependencies = ["prepare"]
description = "Download and extract Prometheus"
script = '''
#!/bin/bash
echo "hello world"
set -e
if [ -d "${PREFIX_BIN}/prometheus" ]; then
    exit 0
fi
if [ -e "${PREFIX_TMP}/prometheus.tar.gz" ]; then
    echo "prometheus.tar.gz exist"
else 
    echo "Prometheus not found, download ${PROMETHEUS_RELEASE}"
    curl -fL -o "${PROMETHEUS_DOWNLOAD_PATH}" "${PROMETHEUS_DOWNLOAD_TAR_GZ}"
fi
echo ${PROMETHEUS_DOWNLOAD_PATH}
tar -xf "${PROMETHEUS_DOWNLOAD_PATH}" -C "${PREFIX_TMP}"
echo ${PREFIX_TMP}
mv "${PREFIX_TMP}/${PROMETHEUS_RELEASE}" "${PREFIX_BIN}/prometheus"
cp /home/ivic/workspace/RunKV/make/prometheus.yml  "${PREFIX_BIN}/prometheus/"
cd "${PREFIX_BIN}/prometheus"
./prometheus --config.file=prometheus.yml --web.listen-address=:9091
cd "${CUR_DIR}"
#rm ${PROMETHEUS_DOWNLOAD_PATH}
echo "pth end"
'''