on:
  pull_request:
    branches: [main]
env:
  RUST_TOOLCHAIN: nightly-2022-02-21
  CARGO_TERM_COLOR: always
jobs:
  rust-test:
    name: rust-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install rust toolchain@v1
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
      - name: Cache Cargo home
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install cargo-tarpaulin
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cargo install cargo-tarpaulin
      - name: Run rust test with coverage
        run: |
          make rust_test_with_coverage
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      